# Generated by Django 6.0.7 on 2026-07-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_game_release_year_game_image_game_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
