# Generated by Django 6.0.7 on 2026-07-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_game_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='platform',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='game',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
