# Generated by Django 6.0.7 on 2026-07-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_game_platform_alter_game_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('Playing', 'Playing'), ('Completed', 'Completed'), ('Plan to Play', 'Plan to Play'), ('Dropped', 'Dropped')], default='Plan to Play', max_length=20),
        ),
    ]
