# Generated by Django 6.0.7 on 2026-07-29 14:06

import api.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_game_rawg_game_id_order_city_order_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='seller_contact',
            field=models.CharField(default='0000000000', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(upload_to='marketplace_images/', validators=[api.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='CheckoutOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10)),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['phone_number', 'is_used'], name='api_checkou_phone_n_41d78e_idx')],
            },
        ),
        migrations.CreateModel(
            name='RentalListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('category', models.CharField(default='Physical Game', max_length=30)),
                ('condition', models.CharField(choices=[('New', 'New — sealed/unused'), ('Like New', 'Like New — barely used'), ('Good', 'Good — normal wear'), ('Fair', 'Fair — visible wear, fully working')], default='Good', max_length=20)),
                ('rental_period', models.IntegerField(choices=[(7, '7 Days'), (14, '14 Days'), (30, '30 Days')])),
                ('rental_charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='rental_images/', validators=[api.validators.validate_image_file])),
                ('owner_contact', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Rented', 'Rented'), ('Removed', 'Removed')], default='Available', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
