# Generated by Django 6.0.7 on 2026-08-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rentalorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedRawgResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=255)),
                ('query_params', models.CharField(blank=True, max_length=500)),
                ('data', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('endpoint', 'query_params')},
            },
        ),
    ]
