# Generated by Django 6.0.7 on 2026-08-03 07:25

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_dispute'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='marketplace_images/', validators=[api.validators.validate_image_file]),
        ),
        migrations.AddField(
            model_name='listing',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='marketplace_images/', validators=[api.validators.validate_image_file]),
        ),
        migrations.AddField(
            model_name='listing',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='marketplace_images/', validators=[api.validators.validate_image_file]),
        ),
        migrations.AddField(
            model_name='rentallisting',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='rental_images/', validators=[api.validators.validate_image_file]),
        ),
        migrations.AddField(
            model_name='rentallisting',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='rental_images/', validators=[api.validators.validate_image_file]),
        ),
        migrations.AddField(
            model_name='rentallisting',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='rental_images/', validators=[api.validators.validate_image_file]),
        ),
    ]
